/*
-- Query: SELECT * FROM pokemon_go.forms
-- Date: 2021-10-30 06:05
*/
INSERT INTO `` (`f_id`,`form_name`) VALUES (1,'');
INSERT INTO `` (`f_id`,`form_name`) VALUES (2,'Alola');
INSERT INTO `` (`f_id`,`form_name`) VALUES (19,'Altered');
INSERT INTO `` (`f_id`,`form_name`) VALUES (51,'Aria');
INSERT INTO `` (`f_id`,`form_name`) VALUES (4,'Armored');
INSERT INTO `` (`f_id`,`form_name`) VALUES (42,'Autumn');
INSERT INTO `` (`f_id`,`form_name`) VALUES (47,'Black');
INSERT INTO `` (`f_id`,`form_name`) VALUES (23,'Bug');
INSERT INTO `` (`f_id`,`form_name`) VALUES (53,'Burn');
INSERT INTO `` (`f_id`,`form_name`) VALUES (54,'Chill');
INSERT INTO `` (`f_id`,`form_name`) VALUES (24,'Dark');
INSERT INTO `` (`f_id`,`form_name`) VALUES (55,'Douse');
INSERT INTO `` (`f_id`,`form_name`) VALUES (25,'Dragon');
INSERT INTO `` (`f_id`,`form_name`) VALUES (12,'East');
INSERT INTO `` (`f_id`,`form_name`) VALUES (26,'Electric');
INSERT INTO `` (`f_id`,`form_name`) VALUES (27,'Fairy');
INSERT INTO `` (`f_id`,`form_name`) VALUES (14,'Fan');
INSERT INTO `` (`f_id`,`form_name`) VALUES (28,'Fighting');
INSERT INTO `` (`f_id`,`form_name`) VALUES (29,'Fire');
INSERT INTO `` (`f_id`,`form_name`) VALUES (30,'Flying');
INSERT INTO `` (`f_id`,`form_name`) VALUES (15,'Frost');
INSERT INTO `` (`f_id`,`form_name`) VALUES (3,'Galarian');
INSERT INTO `` (`f_id`,`form_name`) VALUES (57,'Galarian Zen');
INSERT INTO `` (`f_id`,`form_name`) VALUES (31,'Ghost');
INSERT INTO `` (`f_id`,`form_name`) VALUES (32,'Grass');
INSERT INTO `` (`f_id`,`form_name`) VALUES (33,'Ground');
INSERT INTO `` (`f_id`,`form_name`) VALUES (16,'Heat');
INSERT INTO `` (`f_id`,`form_name`) VALUES (34,'Ice');
INSERT INTO `` (`f_id`,`form_name`) VALUES (21,'Land');
INSERT INTO `` (`f_id`,`form_name`) VALUES (58,'Mega');
INSERT INTO `` (`f_id`,`form_name`) VALUES (59,'Mega X');
INSERT INTO `` (`f_id`,`form_name`) VALUES (60,'Mega Y');
INSERT INTO `` (`f_id`,`form_name`) VALUES (17,'Mow');
INSERT INTO `` (`f_id`,`form_name`) VALUES (35,'Normal');
INSERT INTO `` (`f_id`,`form_name`) VALUES (49,'Ordinary');
INSERT INTO `` (`f_id`,`form_name`) VALUES (20,'Origin');
INSERT INTO `` (`f_id`,`form_name`) VALUES (8,'Overcast');
INSERT INTO `` (`f_id`,`form_name`) VALUES (52,'Pirouette');
INSERT INTO `` (`f_id`,`form_name`) VALUES (5,'Plant');
INSERT INTO `` (`f_id`,`form_name`) VALUES (36,'Poison');
INSERT INTO `` (`f_id`,`form_name`) VALUES (37,'Psychic');
INSERT INTO `` (`f_id`,`form_name`) VALUES (10,'Rainy');
INSERT INTO `` (`f_id`,`form_name`) VALUES (50,'Resolute');
INSERT INTO `` (`f_id`,`form_name`) VALUES (38,'Rock');
INSERT INTO `` (`f_id`,`form_name`) VALUES (6,'Sandy');
INSERT INTO `` (`f_id`,`form_name`) VALUES (56,'Shock');
INSERT INTO `` (`f_id`,`form_name`) VALUES (22,'Sky');
INSERT INTO `` (`f_id`,`form_name`) VALUES (11,'Snowy');
INSERT INTO `` (`f_id`,`form_name`) VALUES (43,'Spring');
INSERT INTO `` (`f_id`,`form_name`) VALUES (39,'Steel');
INSERT INTO `` (`f_id`,`form_name`) VALUES (44,'Summer');
INSERT INTO `` (`f_id`,`form_name`) VALUES (9,'Sunny');
INSERT INTO `` (`f_id`,`form_name`) VALUES (46,'Therian');
INSERT INTO `` (`f_id`,`form_name`) VALUES (7,'Trash');
INSERT INTO `` (`f_id`,`form_name`) VALUES (18,'Wash');
INSERT INTO `` (`f_id`,`form_name`) VALUES (40,'Water');
INSERT INTO `` (`f_id`,`form_name`) VALUES (13,'West');
INSERT INTO `` (`f_id`,`form_name`) VALUES (48,'White');
INSERT INTO `` (`f_id`,`form_name`) VALUES (45,'Winter');
INSERT INTO `` (`f_id`,`form_name`) VALUES (41,'Zen');
